version: 2

java_tool_options: &java_tool_options >-
  -Dhttp.proxyHost=pkg.proxy.prod.jp.local
  -Dhttps.proxyHost=pkg.proxy.prod.jp.local
  -Dhttp.proxyPort=10080
  -Dhttps.proxyPort=10080
  -Dhttp.nonProxyHosts=artifactory.intra.rakuten-it.com|*.intra.rakuten-it.com
  -Dhttps.nonProxyHosts=artifactory.intra.rakuten-it.com|*.intra.rakuten-it.com

gradle_cache_key: &gradle_cache_key >-
  gradle-
  {{ checksum "build.gradle" }}
  {{ checksum "sdk-utils/build.gradle" }}
  {{ checksum "sample/build.gradle" }}

android-docker-image: &android-docker-image circleci/android@sha256:b6646fdf7457f61825526e7bfce364d8e533da6ceb1cdb98e371e94348ecc834

jobs:
  build:
    docker:
      - image: *android-docker-image
    working_directory: ~/code/workspace
    environment:
      JVM_OPTS: "-Xmx3200m"
    steps:
      - checkout
      - run: git submodule update --init
      - restore_cache:
          key: *gradle_cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *gradle_cache_key
      - run:
          name: Run Tests
          command: ./gradlew check
      - run:
          name: Assemble AAR
          command: ./gradlew assemble
      - run:
          name: Current Version
          command: ./gradlew currentVersion
      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: sdk-utils/build/reports
          destination: reports/
      - store_test_results:
          path: sdk-utils/build/test-results
      - store_artifacts:
          path: sdk-utils/build/outputs/aar
          destination: aar/
      - store_artifacts:
          path: sample/build/outputs/apk
          destination: sample/
      - persist_to_workspace:
          root: ~/code
          paths:
            - workspace

  sonarqube-analysis:
    docker:
      - image: circleci/android@sha256:b6646fdf7457f61825526e7bfce364d8e533da6ceb1cdb98e371e94348ecc834
    working_directory: ~/code/workspace
    environment:
      JAVA_TOOL_OPTIONS: *java_tool_options
    steps:
      - attach_workspace:
          at: ~/code/workspace
      - run:
          name: Run SonarQube
          command: |
            cd workspace
            if $SONARQUBE_ENABLED; then
              ./gradlew sonarqube
            else
              echo "SonarQube is disabled"
            fi

  publish:
    docker:
      - image: *android-docker-image
    working_directory: ~/code
    environment:
      JVM_OPTS: "-Xmx3200m"
    steps:
      - checkout
      - run: git submodule update --init
      - restore_cache:
          key: *gradle_cache_key
      - run:
          name: Decode PGP key to file
          command: |
            if [[ $RELEASE_PGP_KEY_BASE64 != "" ]]; then
                base64 -d <<< $RELEASE_PGP_KEY_BASE64 > ./maven-central-key.gpg
            fi
      - run:
          name: Current Version
          command: ./gradlew cV
      - run:
          name: Publish Artifacts
          command: ./gradlew publish

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - sonarqube-analysis:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - release-verification:
          type: approval
          requires:
            - sonarqube-analysis
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - release-verification
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
